#CREATE SCHEMA FOR THE DATABASE:

CREATE SCHEMA `Gradebook`;

#CREATE TABLES USED FOR THE DATABASE

 CREATE TABLE `Gradebook`.`STUDENT` (
    `FirstName` varchar(255) DEFAULT NULL,
    `LastName` varchar(255) DEFAULT NULL,
    `Major` varchar(255) DEFAULT NULL,
    `StudentID` int UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`StudentID`)
); 

CREATE TABLE `Gradebook`.`SCORE` (
	`StudentID` int UNSIGNED NOT NULL,
    `AssignmentID` int UNSIGNED NOT NULL,
    `POINTS` int UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (`StudentID`, `AssignmentID`)
);

CREATE TABLE `Gradebook`.`ASSIGNMENT` (
    `AssignmentID` int UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `DistributionID` int UNSIGNED NOT NULL,
    `Instance` int UNSIGNED NOT NULL,
    `PointsPossible` int UNSIGNED DEFAULT 0 NOT NULL,
    PRIMARY KEY (`AssignmentID`)
);
    
CREATE TABLE `COURSE` (
    `Department` varchar(255) NOT NULL,
    `CourseNumber` int UNSIGNED NOT NULL,
    `CourseName` varchar(255) NOT NULL,
    `Term` varchar(255) NOT NULL,
    `Year` int UNSIGNED NOT NULL,
    `CourseID` int UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    PRIMARY KEY(`CourseID`)
) ;

CREATE TABLE `ENROLLMENT` (
    `StudentID` int UNSIGNED NOT NULL,
    `CourseID` int UNSIGNED NOT NULL,
    PRIMARY KEY (`StudentID`, `CourseID`)
);

CREATE TABLE `DISTRIBUTION` (
    `DistributionID` int UNSIGNED NOT NULL UNIQUE,
    `CourseID` int UNSIGNED NOT NULL,
    `CategoryName` varchar(30) NOT NULL,
    `Percentage` int UNSIGNED NOT NULL,
    PRIMARY KEY(`DistributionID`)
);



#INSERT COMMANDS USED TO PUT DATA IN TABLES: 
SELECT * FROM STUDENT;

#INSERT STUDENTS INTO THE STUDENT TABLE
INSERT INTO `STUDENT` VALUES('Xavier', 'Brown', 'Computer Science', 02851);
INSERT INTO `STUDENT` VALUES('Kendall', 'Stewart', 'English', 02761);
INSERT INTO `STUDENT` VALUES('Kirah', 'Lopez', 'Computer Engineering', 02656);
INSERT INTO `STUDENT` VALUES('William', 'Craft', 'Biology', 02551);
INSERT INTO `STUDENT` VALUES('Joshua', 'Gimmick', 'Computer Science', 02548);
INSERT INTO `STUDENT` VALUES('Trav', 'Bachman', 'Chemistry', 02367);

#INSERT COURSES INTO THE COURSE TABLE 
SELECT * FROM COURSE;

INSERT INTO `COURSE` VALUES('Math', 158, 'Calculus 2', 'Fall', 2021, 89784);
INSERT INTO `COURSE` VALUES('Computer Science', 450, 'Database Systems', 'Spring', 2021, 83794);
INSERT INTO `COURSE` VALUES('English', 007, 'Technical Writing', 'Fall', 2021, 59038);
INSERT INTO `COURSE` VALUES('Computer Science', 678, 'Senior Project II', 'Spring', 2021, 92850);
INSERT INTO `COURSE` VALUES('Biology', 101, 'Biology I', 'Fall', 2021, 49174);

#INSERT STUDENTS TO BE ENROLLED IN COURSES
SELECT * FROM ENROLLMENT;

#STUDENTS ADDED TO CALC II
INSERT INTO `ENROLLMENT` VALUES(02851, 89784);
INSERT INTO `ENROLLMENT` VALUES(02761, 89784);
INSERT INTO `ENROLLMENT` VALUES(02656, 89784);
INSERT INTO `ENROLLMENT` VALUES(02551, 89784);
INSERT INTO `ENROLLMENT` VALUES(02548, 89784);
INSERT INTO `ENROLLMENT` VALUES(02367, 89784);

#STUDENTS ADDED TO DATABASE SYSTEMS
INSERT INTO `ENROLLMENT` VALUES(02851, 83794);
INSERT INTO `ENROLLMENT` VALUES(02656, 83794);
INSERT INTO `ENROLLMENT` VALUES(02548, 83794);
INSERT INTO `ENROLLMENT` VALUES(02367, 56738);

#STUDENTS ADDED TO TECHNICAL WRITING 
INSERT INTO `ENROLLMENT` VALUES(02851, 59038);
INSERT INTO `ENROLLMENT` VALUES(02761, 59038);
INSERT INTO `ENROLLMENT` VALUES(02548, 59038);
INSERT INTO `ENROLLMENT` VALUES(02367, 59038);

#STUDENTS ADDED TO SENIOR PROJECT II
INSERT INTO `ENROLLMENT` VALUES(02851, 92850);
INSERT INTO `ENROLLMENT` VALUES(02656, 92850);
INSERT INTO `ENROLLMENT` VALUES(02548, 92850);

#STUDENTS ADDED TO BIOLOGY I
INSERT INTO `ENROLLMENT` VALUES(02551, 49174);
INSERT INTO `ENROLLMENT` VALUES(02367, 49174);

#INSERT DISTRIBUTION FOR GRADES 

SELECT * FROM DISTRIBUTION;

#CALC II DISTRIBUTION
INSERT INTO `DISTRIBUTION` VALUES(1, 89784, 'Quiz', 40);
INSERT INTO `DISTRIBUTION` VALUES(2, 89784, 'HW', 20);
INSERT INTO `DISTRIBUTION` VALUES(3, 89784, 'MidTerm', 20);
INSERT INTO `DISTRIBUTION` VALUES(4, 89784, 'Final', 20);

#DATABASE SYSTEM DISTRIBUTION
INSERT INTO `DISTRIBUTION` VALUES(5, 83794, 'Assignments', 30);
INSERT INTO `DISTRIBUTION` VALUES(6, 83794, 'HW', 20);
INSERT INTO `DISTRIBUTION` VALUES(7, 83794, 'MidTerm', 25);
INSERT INTO `DISTRIBUTION` VALUES(8, 83794, 'Final', 25);

#TECHNICAL WRITING DISTRIBUTION
INSERT INTO `DISTRIBUTION` VALUES(9, 59038, 'Writing Assignments', 40);
INSERT INTO `DISTRIBUTION` VALUES(10, 59038, 'HW', 15);
INSERT INTO `DISTRIBUTION` VALUES(11, 59038, 'MidTerm', 20);
INSERT INTO `DISTRIBUTION` VALUES(12, 59038, 'Final Writing Project', 25);

#SENIOR PROJECT DISTRIBUTION
INSERT INTO `DISTRIBUTION` VALUES(13, 92850, 'Assignments', 10);
INSERT INTO `DISTRIBUTION` VALUES(14, 92850, 'HW', 30);
INSERT INTO `DISTRIBUTION` VALUES(15, 92850, 'Project', 30);
INSERT INTO `DISTRIBUTION` VALUES(16, 92850, 'Final Demo', 30);

#BIOLOGY 101 DISTRIBUTION
INSERT INTO `DISTRIBUTION` VALUES(17, 49174, 'Quiz', 20);
INSERT INTO `DISTRIBUTION` VALUES(18, 49174, 'HW', 20);
INSERT INTO `DISTRIBUTION` VALUES(19, 49174, 'Midterm', 30);
INSERT INTO `DISTRIBUTION` VALUES(20, 49174, 'Final', 30);
